core_sets <- read.csv("core_sets.csv")
expansions <- read.csv("expansions.csv")
#Import CSV data generated by scryfall.js
cs <- sample(1:nrow(core_sets),1)
#Randomly sample one core set.
ex <-sample(2:nrow(expansions),5)
#Randomly sample five expansions
ex <- c(1,ex)
#Include the newest expansion.
format <- rbind(core_sets[cs,], expansions[ex,])
#Create one dataframe for all sets in the format.
names(format) <- c("Set Name","Expansion Code","Link")
#Make the column names pretty.
filename <-paste("Random Standard ",Sys.Date(),".csv",sep="")
#Name the file Random Standard {date}.csv.
write.csv(format,filename,row.names=FALSE,quote=FALSE)
#Export the format data to csv.
